[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
airdrop = "GjPcPEmbJ7gXvWMitrHmFG7uYEAah3NTrbNmHdsCsCDo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/alina/.config/solana/id.json"
rpc_url = "http://localhost:8898"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
